<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <TrimmerRootDescriptor Include="TrimRoots.xml" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Remove="Assets\mob.csv" />
    <None Remove=".gitignore" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.0.4" />
    <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="11.0.4" />
    <PackageReference Include="Avalonia.Desktop" Version="11.0.4" />
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.0.4" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.0.4" />
    <PackageReference Include="Avalonia.Xaml.Behaviors" Version="11.0.2" />
    <PackageReference Include="CommunityToolkit.Diagnostics" Version="8.2.1" />
    <PackageReference Include="CommunityToolkit.Labs.Extensions.DependencyInjection" Version="0.0.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
    <PackageReference Include="Cronos" Version="0.7.1" />
    <PackageReference Include="CsvHelper" Version="30.0.1" />
    <PackageReference Include="DynamicData" Version="7.14.2" />
    <PackageReference Include="EntityFrameworkCore.Sqlite.NodaTime" Version="7.0.0" />
    <PackageReference Include="FluentAvaloniaUI" Version="2.0.1" />
    <PackageReference Include="Humanizer.Core" Version="2.14.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="7.0.0" />
    <PackageReference Include="NaturalSort.Extension" Version="4.0.0" />
    <PackageReference Include="NodaTime" Version="3.1.9" />
    <PackageReference Include="Serilog" Version="3.0.1" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="System.Linq.Async" Version="6.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="_data\mob.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="_objectives\booster.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="_objectives\fieldboss.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="_objectives\profile.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
